### ISSUE TITLE
Problem with version 1.0.3

### ISSUE THREAD

**Issue by AnniG** [ptheofan/yii2-statemachine#4]
Hello!
First I want to thank you for this FSM implementation. Using it on my local server which runs php 7.1.9. everything worked fine. But on production server I must use php 7.7.3. You cannot use yii\base\Object there anymore. I figured out that you already fixed this issue in branch v2.x.x-RC2 but obviously more than that has been changed. I cannot get roles working anymore. Any chance that you provide an updated readme? Are you still working on this project at all? I would really be glad if you did :)

**Comment by ptheofan** [comment]
It is indeed updated and works with the latest yii2 version. I actually use it in production projects quite heavily. I barely have any free time but will try my best to update the readme file this weekend.

**Comment by ptheofan** [comment]
I've just pushed the v2.0.0
I've added migration information in the [wiki](https://github.com/ptheofan/yii2-statemachine/wiki/Migrating-to-v2.x.x)

I strongly suggest that you migrate using the conditions. Mostly should be a minor update in the XML files.

Of course, in times of panic, there's the alternative of making a fork of latest v1. and search and replace the `extends Object` with `extends BaseObject`. However, I have to admit that the addition of conditionals has enabled me to do some really awesome stuff very easily and with very clean code.

If you need any further assistance feel free to open another ticket.

**Comment by AnniG** [comment]
Hi Paris, 
wonderful! Thank you so much. I must admit that I already had it working yesterday with branch v2.x.x-RC2 but I was too muddle-headed to realize it :) This really makes things easier.
